name: ConnectFour
version: 0.3.1
main: wut.cholo71796.ConnectFour.ConnectFour
description: Play Connect Four in Minecraft!
author: cholo71796
commands:
   connectfour:
       aliases: [cf, c4]
   tictactoe:
       aliases: [tic, ttt, t3, t]