name: ConnectFour
version: 0.3.2
main: wut.cholo71796.ConnectFour.ConnectFour
description: Play Connect Four in Minecraft!
author: cholo71796
commands:
   connectfour:
       aliases: [cf, c4]
   tictactoe:
       aliases: [tic, ttt, t3, t]
permissions:
    connectfour.play:
        description: Allows players to participate in Connect Four games.
        default: true
    connectfour.start:
        description: Allows players to start Connect Four games.
        default: true
    tictactoe.play:
        description: Allows players to participate in tic-tac-toe games.
        default: true
    tictactoe.start:
        description: Allows players to start tic-tac-toe games.
        default: true